
export enum BOOKING {
    PICKED_UP= "PICKED UP",
    WAITING_FOR_PICKUP ="WAITING FOR PICKUP",
    PROCESS = "PROCESSING",
    PLACED = "ORDER PLACED",
    REJECTED= "REJECTED",
    ORDER_CANCELLED= "ORDER CANCELLED",
    RETURN = "RETURN",
}

