export const STATUS = {
  SUCCESS: "Success",
  FAILED: "Failed",
};

export const USER_RESPONSE = {
  SUCCESS: "Success",
  FAILED: "Failed",
  USER_CREATED: "User Created Successfully",
  USER_EXIST: "User Exist",
  EMAIL_EXISTS: "Email Already Exists",
  USER_DOESNT_EXIST: "User doesn't exist",
  LOGIN_FAILED: "Login failed",
  SIGNUP_FAILED: "Signup Failed",
  INCORRECT_PASSWORD: "Incorrect password",
  NO_TOKEN_PROVIDED: "No token provided",
  INVALID_TOKEN: "Invalid token",
  TOKEN_ERROR: "Failed to authenticate token",
  TOKEN_USER_DOESNT_EXIST: "Token user does not exist",
  GET_USER: "Get User Successfully",
  GET_DOESNT_USER: " Get User Doesn't Successfully",
  GET_ALL_USER: "Get All User Successfully",
  GET_ALL_DOESNT_USER: " Get All User Doesn't Successfully",
  UPDATED_USER_ADDRESS: " User Address Update Successfully",
  UPDATED_DOESNT_USER_ADDRESS: "User Address Update Doesn't Successfully",
  REMOVE_USER_ADDRESS: "Remove User Address Successfully",
  REMOVE_DOESNT_USER_ADDRESS: "Doesn't Removed User Address",
  UPDATED_USER: " User Update Successfully",
  UPDATED_DOESNT_USER: "User Update Doesn't Successfully",
  DELETE_USER: "Delete User Successfully",
  DELETE_DOESNT_USER: "Doesn't Deleted User",
  // SESSION_UPDATE_ERROR: "Failed to update session",
};

export const IMAGE_RESPONSE = {
  SUCCESS: "Success",
  FAILED: "Failed",
  IMAGE_CREATED: "Image Created Successfully",
  GET_IMAGE: "Image Get Successfully",
  GET_DOESNT_IMAGE: "Image Doesn't Get Successfully",
  IMAGE_DOESNT_CREATED: "Image Doesn't Created ",
};

export const PRODUCT_RESPONSE = {
  SUCCESS: "Success",
  FAILED: "Failed",
  PRODUCT_CREATED: "Product Created Successfully",
  PRODUCT_DOESNT_CREATED: "Product Doesn't Created ",
  GET_ALL_PRODUCT: "Product Get Successfully",
  GET_ALL_DOESNT_PRODUCT: "Product Doesn't Get Successfully",
  GET_PRODUCT: "Product Get Successfully",
  GET_DOESNT_PRODUCT: "Product Doesn't Get Successfully",
};

export const CART_RESPONSE = {
  SUCCESS: "Success",
  FAILED: "Failed",
  CART_CREATED: "Cart Created Successfully",
  CART_DOESNT_CREATED: "Cart Doesn't Created ",
  CART_UPDATED: "Cart Updated Successfully",
  CART_DOESNT_UPDATED: "Cart Doesn't Updated ",
  GET_CART: "Get Cart Successfully",
  GET_DOESNT_CART: " Get Cart Doesn't Successfully",
  GET_ALL_CART: "Get All Cart Successfully",
  GET_ALL_DOESNT_CART: " Get All Cart Doesn't Successfully",
  DELETE_CART: "Delete Cart Successfully",
  DELETE_DOESNT_CART: "Doesn't Deleted CART",
};

export const COUPON_RESPONSE = {
  SUCCESS: "Success",
  FAILED: "Failed",
  COUPON_CREATED: "Coupon Created Successfully",
  COUPON_DOESNT_CREATED: "Coupon Doesn't Created ",
  COUPON_UPDATED: "Coupon Updated Successfully",
  COUPON_DOESNT_UPDATED: "Coupon Doesn't Updated ",
  GET_COUPON: "Get Coupon Successfully",
  GET_DOESNT_COUPON: " Get Coupon Doesn't Successfully",
  GET_ALL_COUPON: "Get All Coupon Successfully",
  GET_ALL_DOESNT_COUPON: " Get All Coupon Doesn't Successfully",
  DELETE_COUPON: "Delete Coupon Successfully",
  DELETE_DOESNT_COUPON: "Doesn't Deleted Coupon",
  COUPON_ALREADY_USED: "Coupon Already Used",
  COUPON_EXPRIED: "Coupon Expried",
  COUPON_VERIFIED: "Coupon Verified",
  COUPON_DOESNT_VERIFIED: "Coupon Doesn't Verfied",
};

export const USERCOUPON_RESPONSE = {
  SUCCESS: "Success",
  FAILED: "Failed",
  USERCOUPON_CREATED: "Usercoupon Created Successfully",
  USERCOUPON_DOESNT_CREATED: "Usercoupon Doesn't Created ",
  USERCOUPON_UPDATED: "Usercoupon Updated Successfully",
  USERCOUPON_DOESNT_UPDATED: "Usercoupon Doesn't Updated ",
  GET_USERCOUPON: "Get Usercoupon Successfully",
  GET_DOESNT_USERCOUPON: " Get Usercoupon Doesn't Successfully",
  GET_ALL_USERCOUPON: "Get All Usercoupon Successfully",
  GET_ALL_DOESNT_USERCOUPON: " Get All Usercoupon Doesn't Successfully",
  DELETE_USERCOUPON: "Delete Usercoupon Successfully",
  DELETE_DOESNT_USERCOUPON: "Doesn't Deleted Usercoupon",
  USERCOUPON_ALREADY_USED: "Usercoupon Already Used",
  USERCOUPON_EXPRIED: "Usercoupon Expried",
  USERCOUPON_VERIFIED: "Usercoupon Verified",
  USERCOUPON_DOESNT_VERIFIED: "Usercoupon Doesn't Verfied",
};

export const BOOKING_RESPONSE = {
  SUCCESS: "Success",
  FAILED: "Failed",
  BOOKING_CREATED: "Booking Created Successfully",
  BOOKING_DOESNT_CREATED: "Booking Doesn't Created ",
  BOOKING_UPDATED: "Booking Updated Successfully",
  BOOKING_DOESNT_UPDATED: "Booking Doesn't Updated ",
  GET_BOOKING: "Get Booking Successfully",
  GET_DOESNT_BOOKING: " Get Booking Doesn't Successfully",
  GET_ALL_BOOKING: "Get All Booking Successfully",
  GET_ALL_DOESNT_BOOKING: " Get All Booking Doesn't Successfully",
  DELETE_BOOKING: "Delete Booking Successfully",
  DELETE_DOESNT_BOOKING: "Doesn't Deleted Booking",
};

export const ADDRESS_RESPONSE = {
  SUCCESS: "Success",
  FAILED: "Failed",
  ADDRESS_CREATED: "Address Created Successfully",
  ADDRESS_EXIST: "Address Exist",
  DEFAULT_ADDRESS_CREATED: "Default Address Created Successfully",
  DEFAULT_DOESNT_ADDRESS: "Default Address Exist",
  UPDATED_ADDRESS: "Address Update Successfully",
  UPDATED_DOESNT_ADDRESS: "Address Update Doesn't Successfully",
  REMOVE_ADDRESS: "Remove Address Successfully",
  REMOVE_DOESNT_ADDRESS: "Doesn't Removed Address",
  GET_ADDRESS: "Get Address Successfully",
  GET_DOESNT_ADDRESS: " Get Address Doesn't Successfully",
  GET_ALL_ADDRESS: "Get All Address Successfully",
  GET_ALL_DOESNT_ADDRESS: " Get All Address Doesn't Successfully",
  ADDRESS_LIMIT: "Address Most Of the Stored ",
};
